import type { District } from "../../types/common";

/**
 * GENERATED by scripts/build-district-centers.mjs — edit that script, not this file.
 *
 * For each of Tamil Nadu's 38 districts: the most-interior point of the district (furthest from its
 * boundary) and `jitter`, the safe scatter radius in degrees around it. generateMockData places a
 * district's quarries within ±jitter, which keeps every quarry inside the district it is labelled
 * with while still spreading them far enough apart to read as separate markers on the map.
 */
export const DISTRICT_CENTERS: Record<
  District,
  { lat: number; lng: number; jitter: number }
> = {
  Ariyalur: { lat: 11.207, lng: 79.286, jitter: 0.08 },
  Chengalpattu: { lat: 12.466, lng: 79.952, jitter: 0.08 },
  Chennai: { lat: 13.095, lng: 80.227, jitter: 0.039 },
  Coimbatore: { lat: 11.14, lng: 76.971, jitter: 0.08 },
  Cuddalore: { lat: 11.506, lng: 79.562, jitter: 0.08 },
  Dharmapuri: { lat: 12.159, lng: 78.058, jitter: 0.08 },
  Dindigul: { lat: 10.388, lng: 77.886, jitter: 0.08 },
  Erode: { lat: 11.563, lng: 77.241, jitter: 0.08 },
  Kallakurichi: { lat: 11.826, lng: 79.017, jitter: 0.08 },
  Kanchipuram: { lat: 12.854, lng: 79.789, jitter: 0.067 },
  Kanniyakumari: { lat: 8.309, lng: 77.34, jitter: 0.08 },
  Karur: { lat: 10.928, lng: 78.013, jitter: 0.08 },
  Krishnagiri: { lat: 12.668, lng: 77.924, jitter: 0.08 },
  Madurai: { lat: 9.857, lng: 77.886, jitter: 0.08 },
  Mayiladuthurai: { lat: 11.143, lng: 79.724, jitter: 0.078 },
  Nagapattinam: { lat: 10.403, lng: 79.77, jitter: 0.054 },
  Namakkal: { lat: 11.305, lng: 78.143, jitter: 0.08 },
  Perambalur: { lat: 11.257, lng: 78.91, jitter: 0.08 },
  Pudukkottai: { lat: 10.434, lng: 78.885, jitter: 0.08 },
  Ramanathapuram: { lat: 9.358, lng: 78.561, jitter: 0.08 },
  Ranipet: { lat: 12.953, lng: 79.39, jitter: 0.07 },
  Salem: { lat: 11.75, lng: 78.119, jitter: 0.08 },
  Sivaganga: { lat: 9.955, lng: 78.67, jitter: 0.08 },
  Tenkasi: { lat: 9.11, lng: 77.469, jitter: 0.08 },
  Thanjavur: { lat: 10.786, lng: 79.161, jitter: 0.08 },
  "The Nilgiris": { lat: 11.444, lng: 76.692, jitter: 0.08 },
  Theni: { lat: 9.878, lng: 77.435, jitter: 0.08 },
  Thiruvallur: { lat: 13.322, lng: 80.115, jitter: 0.08 },
  Thiruvarur: { lat: 10.696, lng: 79.5, jitter: 0.08 },
  Tiruchirappalli: { lat: 11.066, lng: 78.529, jitter: 0.08 },
  Tirunelveli: { lat: 8.606, lng: 77.598, jitter: 0.08 },
  Tirupathur: { lat: 12.547, lng: 78.619, jitter: 0.08 },
  Tiruppur: { lat: 10.885, lng: 77.509, jitter: 0.08 },
  Tiruvannamalai: { lat: 12.3, lng: 78.969, jitter: 0.08 },
  Tuticorin: { lat: 9.002, lng: 77.988, jitter: 0.08 },
  Vellore: { lat: 12.897, lng: 79.053, jitter: 0.08 },
  Villupuram: { lat: 12.155, lng: 79.473, jitter: 0.08 },
  Virudhunagar: { lat: 9.441, lng: 77.879, jitter: 0.08 },
};

/** Tamil Nadu's real bounding box — used to clamp jittered coordinates and frame the map. */
export const TN_BOUNDS = {
  minLat: 8.0,
  maxLat: 13.6,
  minLng: 76.2,
  maxLng: 80.4,
};

export const TN_CENTER = { lat: 10.9, lng: 78.4 };
