import type { District } from "../../types/common";

/**
 * GENERATED by scripts/build-quarry-sites.mjs — edit that script, not this file.
 *
 * Real quarry sites in Tamil Nadu, from OpenStreetMap `landuse=quarry` polygons (ODbL). The
 * coordinates and `areaSqM` are real: each entry is an actual pit you can see on satellite
 * imagery. generateMockData places one demo quarry on each site, then hangs entirely fictional
 * operator / licence / volume / violation data off it — see the "Data & sources" note in-app.
 *
 * The matching pit outlines live in public/geo/quarry-sites.geojson, keyed by `siteId`.
 */
export interface QuarrySite {
  siteId: string;
  district: District;
  lat: number;
  lng: number;
  /** Mapped surface area of the pit, in square metres. */
  areaSqM: number;
}

export const QUARRY_SITES: QuarrySite[] = [
  { siteId: "S-W178523251", district: "Ariyalur", lat: 11.07594, lng: 79.154908, areaSqM: 3976244 },
  { siteId: "S-W178523256", district: "Ariyalur", lat: 11.141787, lng: 79.127146, areaSqM: 6944178 },
  { siteId: "S-W647027784", district: "Ariyalur", lat: 11.351701, lng: 79.240959, areaSqM: 6426306 },
  { siteId: "S-W1016786105", district: "Chengalpattu", lat: 12.754027, lng: 79.914467, areaSqM: 510017 },
  { siteId: "S-W30118591", district: "Chengalpattu", lat: 12.953787, lng: 80.110943, areaSqM: 693557 },
  { siteId: "S-W522027779", district: "Chengalpattu", lat: 12.475685, lng: 79.847378, areaSqM: 997414 },
  { siteId: "S-W1532396103", district: "Coimbatore", lat: 10.890152, lng: 77.078241, areaSqM: 1983093 },
  { siteId: "S-W1532396104", district: "Coimbatore", lat: 10.87872, lng: 77.047633, areaSqM: 1719403 },
  { siteId: "S-W66134320", district: "Coimbatore", lat: 10.924251, lng: 76.950912, areaSqM: 1266069 },
  { siteId: "S-W56146167", district: "Cuddalore", lat: 11.522179, lng: 79.478682, areaSqM: 25538974 },
  { siteId: "S-W56400658", district: "Cuddalore", lat: 11.517136, lng: 79.432965, areaSqM: 10588838 },
  { siteId: "S-W982810559", district: "Cuddalore", lat: 11.562298, lng: 79.502792, areaSqM: 20896058 },
  { siteId: "S-W169356604", district: "Dharmapuri", lat: 12.477471, lng: 77.949636, areaSqM: 783918 },
  { siteId: "S-W607113537", district: "Dharmapuri", lat: 12.055944, lng: 78.517009, areaSqM: 31419 },
  { siteId: "S-W129673966", district: "Dindigul", lat: 10.708641, lng: 78.065693, areaSqM: 5089054 },
  { siteId: "S-W1299543124", district: "Dindigul", lat: 10.244112, lng: 78.24217, areaSqM: 165962 },
  { siteId: "S-W297545910", district: "Dindigul", lat: 10.715259, lng: 78.116724, areaSqM: 491999 },
  { siteId: "S-W217269548", district: "Erode", lat: 11.03194, lng: 77.884451, areaSqM: 86582 },
  { siteId: "S-W823591866", district: "Erode", lat: 11.199156, lng: 77.567595, areaSqM: 222307 },
  { siteId: "S-W83800639", district: "Erode", lat: 11.279299, lng: 77.759805, areaSqM: 86411 },
  { siteId: "S-W1119090151", district: "Kallakurichi", lat: 11.667765, lng: 79.205207, areaSqM: 30283 },
  { siteId: "S-W815790484", district: "Kallakurichi", lat: 11.684726, lng: 79.00964, areaSqM: 188827 },
  { siteId: "S-W1016786109", district: "Kanchipuram", lat: 12.724063, lng: 79.851742, areaSqM: 2694950 },
  { siteId: "S-W202471886", district: "Kanchipuram", lat: 12.846683, lng: 79.899437, areaSqM: 1729466 },
  { siteId: "S-W548835208", district: "Kanniyakumari", lat: 8.189847, lng: 77.521358, areaSqM: 220628 },
  { siteId: "S-W551624070", district: "Kanniyakumari", lat: 8.218772, lng: 77.37688, areaSqM: 306162 },
  { siteId: "S-W1009415242", district: "Karur", lat: 10.739435, lng: 78.399978, areaSqM: 765905 },
  { siteId: "S-W1023111996", district: "Karur", lat: 11.05277, lng: 77.780826, areaSqM: 560382 },
  { siteId: "S-W1422346281", district: "Krishnagiri", lat: 12.659698, lng: 77.963138, areaSqM: 570631 },
  { siteId: "S-W534846600", district: "Krishnagiri", lat: 12.740324, lng: 77.941739, areaSqM: 835236 },
  { siteId: "S-W177370710", district: "Madurai", lat: 10.076285, lng: 78.443042, areaSqM: 1900334 },
  { siteId: "S-W177370711", district: "Madurai", lat: 10.059893, lng: 78.40119, areaSqM: 3501574 },
  { siteId: "S-W645607780", district: "Nagapattinam", lat: 10.56169, lng: 79.746773, areaSqM: 165886 },
  { siteId: "S-W82865093", district: "Namakkal", lat: 11.468872, lng: 77.78551, areaSqM: 675526 },
  { siteId: "S-W910321876", district: "Namakkal", lat: 11.077129, lng: 77.964269, areaSqM: 579744 },
  { siteId: "S-W1000546399", district: "Perambalur", lat: 11.116221, lng: 78.842764, areaSqM: 968788 },
  { siteId: "S-W1000546401", district: "Perambalur", lat: 11.222664, lng: 78.918677, areaSqM: 1728551 },
  { siteId: "S-W175584075", district: "Pudukkottai", lat: 10.520935, lng: 78.772821, areaSqM: 544553 },
  { siteId: "S-W555516022", district: "Pudukkottai", lat: 10.390269, lng: 78.795197, areaSqM: 301585 },
  { siteId: "S-W725193693", district: "Ramanathapuram", lat: 9.587062, lng: 78.471475, areaSqM: 31357 },
  { siteId: "S-W1031396681", district: "Ranipet", lat: 12.872648, lng: 79.425364, areaSqM: 5845213 },
  { siteId: "S-W910550467", district: "Ranipet", lat: 12.938255, lng: 79.392984, areaSqM: 1965183 },
  { siteId: "S-W175237649", district: "Salem", lat: 11.475466, lng: 77.811747, areaSqM: 799381 },
  { siteId: "S-W178473259", district: "Salem", lat: 11.561176, lng: 77.852996, areaSqM: 1321642 },
  { siteId: "S-W1154700242", district: "Sivaganga", lat: 10.121058, lng: 78.65947, areaSqM: 180532 },
  { siteId: "S-W297525516", district: "Sivaganga", lat: 9.889563, lng: 78.402876, areaSqM: 141816 },
  { siteId: "S-W1363590609", district: "Tenkasi", lat: 8.990659, lng: 77.236694, areaSqM: 38887 },
  { siteId: "S-W204957218", district: "Tenkasi", lat: 9.091989, lng: 77.388907, areaSqM: 244105 },
  { siteId: "S-W1078863162", district: "Thanjavur", lat: 10.940269, lng: 79.214132, areaSqM: 168197 },
  { siteId: "S-W1543174845", district: "The Nilgiris", lat: 11.319914, lng: 76.544288, areaSqM: 35258 },
  { siteId: "S-W1509428376", district: "Theni", lat: 10.005244, lng: 77.405137, areaSqM: 232057 },
  { siteId: "S-W977532854", district: "Theni", lat: 10.017284, lng: 77.549094, areaSqM: 279093 },
  { siteId: "S-W1250353895", district: "Thiruvallur", lat: 13.281815, lng: 79.597798, areaSqM: 1222951 },
  { siteId: "S-W553897176", district: "Thiruvallur", lat: 13.234802, lng: 80.12634, areaSqM: 587817 },
  { siteId: "S-W178531103", district: "Tiruchirappalli", lat: 10.988115, lng: 78.94608, areaSqM: 702803 },
  { siteId: "S-W178531106", district: "Tiruchirappalli", lat: 10.959442, lng: 78.934106, areaSqM: 585759 },
  { siteId: "S-W206074310", district: "Tirunelveli", lat: 8.817698, lng: 77.730266, areaSqM: 2803051 },
  { siteId: "S-W206074313", district: "Tirunelveli", lat: 8.795934, lng: 77.674039, areaSqM: 6337599 },
  { siteId: "S-W1539560683", district: "Tirupathur", lat: 12.726936, lng: 78.695233, areaSqM: 509351 },
  { siteId: "S-W534352275", district: "Tirupathur", lat: 12.855313, lng: 78.887839, areaSqM: 156807 },
  { siteId: "S-W984559658", district: "Tiruppur", lat: 10.652107, lng: 77.563175, areaSqM: 329507 },
  { siteId: "S-W985084122", district: "Tiruppur", lat: 11.06915, lng: 77.585636, areaSqM: 334155 },
  { siteId: "S-W535231949", district: "Tiruvannamalai", lat: 12.70344, lng: 79.182186, areaSqM: 27249 },
  { siteId: "S-W535232077", district: "Tiruvannamalai", lat: 12.697923, lng: 79.223129, areaSqM: 34110 },
  { siteId: "S-W1032774973", district: "Thoothukudi", lat: 8.666512, lng: 77.920765, areaSqM: 3247275 },
  { siteId: "S-W193315729", district: "Thoothukudi", lat: 9.313482, lng: 78.153542, areaSqM: 3894236 },
  { siteId: "S-W1167672530", district: "Vellore", lat: 12.850184, lng: 79.12744, areaSqM: 143590 },
  { siteId: "S-W138986550", district: "Vellore", lat: 12.865359, lng: 79.110968, areaSqM: 612141 },
  { siteId: "S-W1026841609", district: "Villupuram", lat: 12.053806, lng: 79.655821, areaSqM: 7149387 },
  { siteId: "S-W1026841613", district: "Villupuram", lat: 12.215218, lng: 79.758449, areaSqM: 2814722 },
  { siteId: "S-W1151596289", district: "Virudhunagar", lat: 9.472709, lng: 78.190191, areaSqM: 3243898 },
  { siteId: "S-W297525511", district: "Virudhunagar", lat: 9.370491, lng: 78.170019, areaSqM: 6062857 },
];
