import type { VehicleTrip } from "../types/transport";

export function generateTransportViolationSummary(trip: VehicleTrip): { english: string; tamil: string } {
  if (trip.status === "Compliant") {
    return {
      english: "Vehicle is operating compliantly within declared routes.",
      tamil: "வாகனம் அறிவிக்கப்பட்ட வழிகளுக்குள் இணக்கமாக இயங்குகிறது.",
    };
  }

  const borderInfo = trip.hasCrossedBorder 
    ? `has crossed the ${trip.borderState} border` 
    : `is suspiciously approaching the ${trip.borderState} border`;
    
  const action = trip.hasCrossedBorder ? "கடந்துள்ளது" : "சந்தேகத்திற்கிடமான முறையில் நெருங்குகிறது";
    
  return {
    english: `Violation Detected: Vehicle ${trip.vehicleNumber} carrying ${trip.declaredWeightTonnes} tonnes of ${trip.mineralType} ${borderInfo} without a valid permit (Status: ${trip.permitStatus}). The actual GPS route significantly deviates from the declared destination (${trip.declaredDestination}). Immediate interception is recommended.`,
    tamil: `விதிமீறல் கண்டறியப்பட்டுள்ளது: ${trip.declaredWeightTonnes} டன்கள் ${trip.mineralType} ஏற்றிச் செல்லும் ${trip.vehicleNumber} என்ற வாகனம் செல்லுபடியாகும் அனுமதி இல்லாமல் (நிலை: ${trip.permitStatus}) ${trip.borderState} எல்லையை ${action}. உண்மையான ஜிபிஎஸ் பாதை அறிவிக்கப்பட்ட இலக்கிலிருந்து (${trip.declaredDestination}) கணிசமாக விலகுகிறது. உடனடியாக வாகனத்தை மறிக்க பரிந்துரைக்கப்படுகிறது.`,
  };
}

export function draftFIRDraft(trip: VehicleTrip): string {
  const today = new Date().toLocaleDateString("en-IN");
  
  return `FIRST INFORMATION REPORT (FIR) DRAFT
(Under Section 154 Cr.P.C.)

1. Date and Time of Report: ${today}
2. Place of Occurrence: Near ${trip.borderState} Border Checkpost
3. Details of Vehicle:
   - Registration No: ${trip.vehicleNumber}
   - Driver Name: ${trip.driverName}
   - Operator Name: ${trip.operatorName}
4. Nature of Offence:
   Illegal inter-state transport of minerals without valid e-permit.
   Vehicle intercepted while transporting ${trip.declaredWeightTonnes} tonnes of ${trip.mineralType}.
   Permit Status at time of checking: ${trip.permitStatus}.
   Declared Destination was ${trip.declaredDestination}, but actual GPS path indicates intent to cross state borders.
5. Action Taken:
   Vehicle blocked remotely. Alert sent to nearest Border Police Station for physical seizure of vehicle and materials.

Draft generated by AI Transport Monitoring System.`;
}
